title: Hello, world! I'm Leonardo Leon
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/mywebsite" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Leonardo Leon # add your name
author-img: leonardo-leon.png # add your photo
about-author: I am a Computer Vision and Machine Learning Engineer. Always hungry to keep learning. # add description
social-twitter: _lleonv
social-facebook: Lleonv20
social-github: leo2105
social-linkedin: lleonv/
social-email: lleonv@uni.pe

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
